import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
                'resources/js/admin.js',
                'resources/css/admin.css',
                'frontend_assets/sass/home/home.css',
                'frontend_assets/css/blogs.css',
                'frontend_assets/css/developers.css',
                'frontend_assets/css/hoztab.css',
                'frontend_assets/css/allprojects.css',
                'frontend_assets/css/aresponsive.css',
                'frontend_assets/css/contact.css',
                'frontend_assets/css/property.css',
                'frontend_assets/css/fancybox.css',
                'frontend_assets/js/main.js',
                'frontend_assets/js/svg-loader.js',
                'frontend_assets/images/fav_sec.png',
                'frontend_assets/images/fav.png',
                'frontend_assets/images/logo.png',
                'frontend_assets/images/main_logo.png',
                'frontend_assets/images/home/bfacebook.png',
                'frontend_assets/images/home/btwitter.png',
                'frontend_assets/images/home/blinkedin.png',
                'frontend_assets/images/home/bwhatsapp.png',
                'frontend_assets/images/home/bemail.png',
                'frontend_assets/icon/search.svg',
                'frontend_assets/icon/mappin1.svg',
                'frontend_assets/icon/rupee.svg',
                'frontend_assets/icon/hotel.svg',
                'frontend_assets/icon/top-right.svg',
                'frontend_assets/icon/right-arrow.svg',
                'frontend_assets/icon/blogshare.svg',
                'frontend_assets/icon/formicon.svg',
                'frontend_assets/icon/icons8-call.gif',
                'admin_assets/images/main_logo.png',
                'frontend_assets/icon/quotes.svg',
                'frontend_assets/icon/stars.svg',
                'frontend_assets/icon/adlocation.png',
                'frontend_assets/icon/admail.png',
                'frontend_assets/icon/adphone.png',
                'resources/css/custom.css',
                'frontend_assets/images/home/fixedbg.webp',
                'frontend_assets/images/home/footer_bg.jpg',
                'frontend_assets/images/bg1.webp',
                'frontend_assets/font/Champignon.ttf',
                'frontend_assets/images/about/founder.webp',
                'frontend_assets/images/about/vision.webp',
                'frontend_assets/images/about/mission.webp',
                'frontend_assets/images/about/strength.webp',
                'frontend_assets/images/about/texture-bg.webp', 
                'frontend_assets/images/awards/award-1.png',
                'frontend_assets/images/awards/award-2.png',
                'frontend_assets/images/awards/award-3.png',
                'frontend_assets/images/awards/award-4.png',
                'frontend_assets/js/about.js',
                // Admin Assets
                'admin_assets/css/app.css',
                'admin_assets/css/app.min.css',
                'admin_assets/css/bootstrap.css',
                'admin_assets/css/bootstrap.min.css',
                'admin_assets/css/icons.css',
                'admin_assets/css/icons.min.css',
                'admin_assets/css/preloader.css',
                'admin_assets/css/preloader.min.css',
                'admin_assets/css/abhi-custom.css',
                'admin_assets/libs/select2/css/select2.min.css',
                'admin_assets/libs/dropzone/min/dropzone.min.css',
                'admin_assets/libs/sweetalert2/sweetalert2.min.css',
                'admin_assets/libs/admin-resources/jquery.vectormap/jquery-jvectormap-1.2.2.css',
                'admin_assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css',
                'admin_assets/libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css',
                'admin_assets/libs/choices.js/public/assets/styles/choices.min.css',
                'admin_assets/js/app.js',
                'admin_assets/libs/jquery/jquery.min.js',
                'admin_assets/libs/bootstrap/js/bootstrap.bundle.min.js',
                'admin_assets/libs/metismenu/metisMenu.min.js',
                'admin_assets/libs/simplebar/simplebar.min.js',
                'admin_assets/libs/node-waves/waves.min.js',
                'admin_assets/libs/feather-icons/feather.min.js',
                'admin_assets/libs/pace-js/pace.min.js',
                'admin_assets/js/pages/pass-addon.init.js',
                'admin_assets/js/pages/feather-icon.init.js',
                'admin_assets/js/pages/dashboard.init.js',
                'admin_assets/libs/select2/js/select2.min.js',
                'admin_assets/libs/dropzone/min/dropzone.min.js',
                'admin_assets/libs/sweetalert2/sweetalert2.min.js',
                'admin_assets/libs/admin-resources/jquery.vectormap/jquery-jvectormap-1.2.2.min.js',
                'admin_assets/libs/admin-resources/jquery.vectormap/maps/jquery-jvectormap-world-mill-en.js',
                'admin_assets/js/pages/allchart.js',
                'admin_assets/libs/datatables.net/js/jquery.dataTables.min.js',
                'admin_assets/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js',
                'admin_assets/libs/datatables.net-responsive/js/dataTables.responsive.min.js',
                'admin_assets/libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js',
                'admin_assets/js/pages/datatable-pages.init.js',
                'admin_assets/libs/tinymce/tinymce.min.js',
                'admin_assets/libs/jquery.repeater/jquery.repeater.min.js',
                'admin_assets/js/pages/task-create.init.js',
                'admin_assets/libs/@ckeditor/ckeditor5-build-classic/build/ckeditor.js',
                'admin_assets/libs/jquery-knob/jquery.knob.min.js',
                'admin_assets/js/pages/jquery-knob.init.js',
                'admin_assets/js/pages/sweetalert.init.js',
                'admin_assets/js/pages/ecommerce-select2.init.js',
                'admin_assets/js/pages/form-advanced.init.js',
                'admin_assets/libs/choices.js/public/assets/scripts/choices.min.js',
                'admin_assets/libs/apexcharts/apexcharts.min.js',
                // 'admin_assets/images/favicon.png', // Removed as it does not exist
                
            ],
            refresh: true,
        }),
    ],
    build: {
        outDir: 'public/build',
        rollupOptions: {
            output: {
                assetFileNames: (assetInfo) => {
                    let extType = assetInfo.name.split('.').at(1);
                    if (/png|jpe?g|svg|gif|tiff|bmp|ico|webp/i.test(extType)) {
                        extType = 'img';
                    }
                    return `assets/${extType}/[name]-[hash][extname]`;
                },
                chunkFileNames: 'assets/js/[name]-[hash].js',
                entryFileNames: 'assets/js/[name]-[hash].js',
            },
        },
    },
});
